import { Trip } from './types';

// Helper to create placeholder images (using Unsplash source)
const img = (seed: string, index: number = 1) =>
  `https://source.unsplash.com/800x600/?${seed},${index}`;

export const mockTrip: Trip = {
  id: '1',
  title: "Brian O'Mahony's New Zealand Adventure",
  location: 'Aotearoa, NZ, Australasia',
  creator: 'Sarah Chen',
  createdAt: new Date('2025-02-15'),
  expiresAt: new Date('2025-03-01'),
  stats: {
    days: 3,
    stays: 2,
    experiences: 6,
  },
  status: 'sent',
  changeLog: [],
  itinerary: [
    // =======================
    // DAY 1: ARRIVE AUCKLAND
    // =======================
    {
      date: 'Wednesday 5 Mar 2025',
      dayNumber: 1,
      activities: [
        // Transfer (Locked)
        {
          id: '1-transfer',
          title: 'Airport to Hotel Transfer',
          type: 'transfer',
          time: '10:30 AM',
          duration: '45 min',
          locked: true,
          location: {
            id: 'akl-airport',
            name: 'Auckland Airport',
            coordinates: [-37.0082, 174.7850],
          },
          options: [
            {
              id: 'transfer-private',
              name: 'Private Car Transfer',
              description: 'Comfortable private transfer with meet & greet service',
              price: 120,
              statusCredits: 50,
              societePoints: 10,
              photos: [img('car,transfer')],
              inclusions: ['Meet & greet at arrivals', 'All tolls included', 'Complimentary water', 'Luggage assistance'],
              exclusions: [],
              cancellationPolicy: 'Free cancellation up to 24 hours',
              availability: 'available',
            },
          ],
          selectedOptionId: 'transfer-private',
          agentRecommendedOptionId: 'transfer-private',
        },

        // Auckland Hotel (Multiple Options)
        {
          id: '1-hotel',
          title: 'Auckland Accommodation',
          type: 'hotel',
          time: '12:00 PM',
          duration: '1 night',
          locked: false,
          location: {
            id: 'akl-viaduct',
            name: 'Viaduct Harbour, Auckland',
            coordinates: [-36.8425, 174.7611],
          },
          constraints: {
            minNights: 1,
            maxNights: 2,
          },
          options: [
            {
              id: 'hotel-sofitel',
              name: 'Sofitel Auckland Viaduct Harbour',
              description: 'Luxurious 5-star waterfront hotel with stunning harbour views. Agent recommended for first-time visitors.',
              price: 450,
              statusCredits: 180,
              societePoints: 45,
              photos: [img('luxury,hotel,auckland', 1), img('luxury,hotel,room', 2), img('hotel,pool', 3)],
              inclusions: ['Harbour view room', 'Daily breakfast', 'WiFi', 'Gym & pool access', 'Late checkout (2 PM)'],
              exclusions: ['Parking ($45/day)', 'Mini-bar'],
              cancellationPolicy: 'Free cancellation until 2 days before arrival',
              availability: 'available',
              supplier: {
                name: 'Sofitel',
                rating: 4.7,
                reviewCount: 2845,
              },
              roomType: 'Luxury Harbour View',
              mealPlan: 'Breakfast included',
              highlights: ['Waterfront location', 'Award-winning restaurant', 'Close to city attractions'],
            },
            {
              id: 'hotel-skycity',
              name: 'SkyCity Hotel',
              description: 'Modern hotel connected to Sky Tower and casino complex. Great for entertainment.',
              price: 380,
              statusCredits: 150,
              societePoints: 38,
              photos: [img('modern,hotel,auckland', 1), img('hotel,room,modern', 2)],
              inclusions: ['Deluxe room', 'WiFi', 'Gym access', 'Sky Tower discounts'],
              exclusions: ['Breakfast', 'Parking ($40/day)'],
              cancellationPolicy: 'Free cancellation until 3 days before arrival',
              availability: 'available',
              supplier: {
                name: 'SkyCity Hotels',
                rating: 4.5,
                reviewCount: 1920,
              },
              roomType: 'Deluxe',
              mealPlan: 'Room only',
              highlights: ['Connected to Sky Tower', 'Multiple dining options', 'Casino access'],
            },
            {
              id: 'hotel-cordis',
              name: 'Cordis Auckland',
              description: 'Upscale hotel near Eden Park with spacious rooms and excellent service.',
              price: 420,
              statusCredits: 165,
              societePoints: 42,
              photos: [img('elegant,hotel,room', 1), img('hotel,spa', 2)],
              inclusions: ['Superior room', 'Daily breakfast', 'WiFi', 'Pool & spa access', 'Free parking'],
              exclusions: ['Mini-bar', 'Room service'],
              cancellationPolicy: 'Free cancellation until 2 days before arrival',
              availability: 'limited',
              supplier: {
                name: 'Cordis Hotels',
                rating: 4.6,
                reviewCount: 1543,
              },
              roomType: 'Superior',
              mealPlan: 'Breakfast included',
              highlights: ['Free parking', 'Beautiful gardens', 'Near Eden Park'],
            },
          ],
          selectedOptionId: 'hotel-sofitel',
          agentRecommendedOptionId: 'hotel-sofitel',
          notes: 'The Sofitel is my top pick for waterfront views and proximity to restaurants',
          addedBy: {
            name: 'Sarah',
          },
        },

        // Afternoon Activity (Multiple Options)
        {
          id: '1-activity',
          title: 'Afternoon Experience',
          type: 'activity',
          time: '2:00 PM',
          duration: '3 hr',
          locked: false,
          location: {
            id: 'sky-tower',
            name: 'Sky Tower',
            coordinates: [-36.8485, 174.7633],
          },
          options: [
            {
              id: 'act-skywalk',
              name: 'Sky Tower SkyWalk',
              description: 'Walk around the exterior of the Sky Tower at 192m high! An exhilarating experience.',
              price: 175,
              statusCredits: 85,
              societePoints: 18,
              photos: [img('skytower,walk,adventure', 1), img('skytower,auckland', 2)],
              inclusions: ['Harness and safety gear', 'Professional guide', 'Souvenir photo', 'Certificate of bravery'],
              exclusions: ['Food and drinks'],
              cancellationPolicy: 'Free cancellation up to 48 hours before',
              availability: 'available',
              supplier: {
                name: 'SkyCity Attractions',
                rating: 4.8,
                reviewCount: 3210,
              },
              highlights: ['360° views', 'Adrenaline rush', 'Perfect for thrill-seekers'],
            },
            {
              id: 'act-observatory',
              name: 'Sky Tower Observatory Deck',
              description: 'Enjoy 360-degree views of Auckland from the observation deck. More relaxed option.',
              price: 35,
              statusCredits: 15,
              societePoints: 4,
              photos: [img('observation,deck,view', 1), img('city,skyline', 2)],
              inclusions: ['Access to 3 observation levels', 'High-powered binoculars', 'Audio guide'],
              exclusions: ['Sky Jump', 'Cafe purchases'],
              cancellationPolicy: 'Free cancellation up to 24 hours before',
              availability: 'available',
              supplier: {
                name: 'SkyCity Attractions',
                rating: 4.6,
                reviewCount: 5420,
              },
              highlights: ['Budget-friendly', 'Great views', 'No height restrictions'],
            },
            {
              id: 'act-museum',
              name: 'Auckland War Memorial Museum',
              description: 'Explore Māori culture, natural history, and war history in this iconic museum.',
              price: 45,
              statusCredits: 20,
              societePoints: 5,
              photos: [img('museum,maori,culture', 1), img('museum,auckland', 2)],
              inclusions: ['General admission', 'Māori cultural performance', 'Audio guide'],
              exclusions: ['Special exhibitions'],
              cancellationPolicy: 'Free cancellation up to 24 hours before',
              availability: 'available',
              supplier: {
                name: 'Auckland Museum',
                rating: 4.7,
                reviewCount: 4180,
              },
              highlights: ['Cultural insights', 'Family-friendly', 'Educational'],
            },
          ],
          selectedOptionId: 'act-skywalk',
          agentRecommendedOptionId: 'act-skywalk',
          notes: 'The SkyWalk is unforgettable if you are comfortable with heights!',
          addedBy: {
            name: 'Sarah',
          },
        },

        // Dinner
        {
          id: '1-dinner',
          title: 'Dinner',
          type: 'dining',
          time: '7:00 PM',
          duration: '2 hr',
          locked: false,
          location: {
            id: 'viaduct',
            name: 'Viaduct Harbour',
            coordinates: [-36.8425, 174.7611],
          },
          options: [
            {
              id: 'dinner-orbit',
              name: 'Orbit 360° Dining',
              description: 'Revolving restaurant atop Sky Tower with fine dining and panoramic views.',
              price: 185,
              statusCredits: 75,
              societePoints: 19,
              photos: [img('fine,dining,view', 1), img('restaurant,luxury', 2)],
              inclusions: ['3-course dinner', 'Window seat guaranteed', 'Complimentary wine pairing'],
              exclusions: ['Additional drinks', 'Gratuity'],
              cancellationPolicy: 'Free cancellation up to 48 hours before',
              availability: 'available',
              supplier: {
                name: 'Orbit Restaurant',
                rating: 4.5,
                reviewCount: 892,
              },
              highlights: ['Rotating views', 'Fine dining', 'Romantic setting'],
            },
            {
              id: 'dinner-viaduct',
              name: 'Viaduct Harbour Seafood',
              description: 'Fresh seafood at a waterfront restaurant in the vibrant Viaduct precinct.',
              price: 120,
              statusCredits: 50,
              societePoints: 12,
              photos: [img('seafood,restaurant', 1), img('harbour,dining', 2)],
              inclusions: ['2-course dinner', 'Table wine', 'Harbour views'],
              exclusions: ['Dessert', 'Premium drinks'],
              cancellationPolicy: 'Free cancellation up to 24 hours before',
              availability: 'available',
              supplier: {
                name: 'Soul Bar & Bistro',
                rating: 4.6,
                reviewCount: 1245,
              },
              highlights: ['Fresh seafood', 'Lively atmosphere', 'Great location'],
            },
          ],
          selectedOptionId: 'dinner-orbit',
          agentRecommendedOptionId: 'dinner-orbit',
        },
      ],
    },

    // =======================
    // DAY 2: ROTORUA
    // =======================
    {
      date: 'Thursday 6 Mar 2025',
      dayNumber: 2,
      activities: [
        // Drive to Rotorua (Locked)
        {
          id: '2-drive',
          title: 'Scenic Drive to Rotorua',
          type: 'transfer',
          time: '9:00 AM',
          duration: '3 hr',
          locked: true,
          location: {
            id: 'rotorua',
            name: 'Rotorua',
            coordinates: [-38.1368, 176.2497],
          },
          options: [
            {
              id: 'drive-self',
              name: 'Self-drive with rental car',
              description: 'Scenic route through Waikato farmland to Rotorua',
              price: 0,
              statusCredits: 0,
              societePoints: 0,
              photos: [img('road,newzealand', 1)],
              inclusions: ['Suggested route', 'Stop recommendations'],
              exclusions: ['Rental car fee (separate)', 'Fuel'],
              cancellationPolicy: 'N/A',
              availability: 'available',
            },
          ],
          selectedOptionId: 'drive-self',
          agentRecommendedOptionId: 'drive-self',
        },

        // Māori Cultural Experience
        {
          id: '2-maori',
          title: 'Māori Cultural Experience',
          type: 'experience',
          time: '1:00 PM',
          duration: '4 hr',
          locked: false,
          location: {
            id: 'tamaki',
            name: 'Tamaki Māori Village',
            coordinates: [-38.2008, 176.2506],
          },
          options: [
            {
              id: 'maori-tamaki',
              name: 'Tamaki Māori Village Experience',
              description: 'Authentic Māori cultural experience with traditional hangi feast and performances.',
              price: 195,
              statusCredits: 80,
              societePoints: 20,
              photos: [img('maori,performance', 1), img('hangi,food', 2), img('maori,village', 3)],
              inclusions: ['Village tour', 'Cultural performance', 'Hangi feast dinner', 'Transportation from Rotorua'],
              exclusions: ['Drinks', 'Photos'],
              cancellationPolicy: 'Free cancellation up to 48 hours before',
              availability: 'available',
              supplier: {
                name: 'Tamaki Māori Village',
                rating: 4.9,
                reviewCount: 5234,
              },
              highlights: ['#1 cultural experience NZ', 'Authentic hangi dinner', 'Award-winning'],
            },
            {
              id: 'maori-mitai',
              name: 'Mitai Māori Village',
              description: 'Traditional Māori cultural performance in natural forest setting with glowworm grotto.',
              price: 165,
              statusCredits: 70,
              societePoints: 17,
              photos: [img('maori,culture', 1), img('traditional,performance', 2)],
              inclusions: ['Forest walk', 'Cultural show', 'Hangi buffet', 'Glowworm viewing'],
              exclusions: ['Drinks', 'Hotel pickup'],
              cancellationPolicy: 'Free cancellation up to 48 hours before',
              availability: 'available',
              supplier: {
                name: 'Mitai Māori Village',
                rating: 4.7,
                reviewCount: 2891,
              },
              highlights: ['Glowworm grotto', 'Forest setting', 'Smaller groups'],
            },
          ],
          selectedOptionId: 'maori-tamaki',
          agentRecommendedOptionId: 'maori-tamaki',
          notes: 'Tamaki is the premium option - absolutely worth it!',
          addedBy: {
            name: 'Sarah',
          },
        },

        // Rotorua Hotel
        {
          id: '2-hotel',
          title: 'Rotorua Accommodation',
          type: 'hotel',
          time: '7:00 PM',
          duration: '1 night',
          locked: false,
          location: {
            id: 'rotorua-lakefront',
            name: 'Rotorua Lakefront',
            coordinates: [-38.1341, 176.2572],
          },
          constraints: {
            minNights: 1,
            maxNights: 3,
          },
          options: [
            {
              id: 'hotel-solitaire',
              name: 'Solitaire Lodge',
              description: 'Luxury boutique lodge on Lake Tarawera with stunning views and personalized service.',
              price: 890,
              statusCredits: 350,
              societePoints: 89,
              photos: [img('luxury,lodge,lake', 1), img('boutique,hotel,room', 2), img('lake,view', 3)],
              inclusions: ['Lake view suite', 'Gourmet breakfast & dinner', 'Complimentary spa treatment', 'WiFi', 'All activities on property'],
              exclusions: [],
              cancellationPolicy: 'Free cancellation until 7 days before',
              availability: 'limited',
              supplier: {
                name: 'Solitaire Lodge',
                rating: 4.9,
                reviewCount: 421,
              },
              roomType: 'Lake View Suite',
              mealPlan: 'Breakfast & Dinner included',
              highlights: ['Ultra-luxury', 'Secluded lakefront', 'All-inclusive'],
            },
            {
              id: 'hotel-polynesian',
              name: 'Polynesian Spa Hotel',
              description: 'Modern lakefront hotel with direct access to Polynesian Spa pools.',
              price: 385,
              statusCredits: 155,
              societePoints: 39,
              photos: [img('spa,hotel', 1), img('lakefront,room', 2)],
              inclusions: ['Lake view room', 'Breakfast', 'Spa pool access', 'WiFi', 'Parking'],
              exclusions: ['Mini-bar', 'Spa treatments'],
              cancellationPolicy: 'Free cancellation until 2 days before',
              availability: 'available',
              supplier: {
                name: 'Millennium Hotels',
                rating: 4.4,
                reviewCount: 1876,
              },
              roomType: 'Lake View',
              mealPlan: 'Breakfast included',
              highlights: ['Spa access', 'Central location', 'Lake views'],
            },
            {
              id: 'hotel-novotel',
              name: 'Novotel Rotorua Lakeside',
              description: 'Well-appointed hotel right on the lakefront with modern amenities.',
              price: 320,
              statusCredits: 130,
              societePoints: 32,
              photos: [img('modern,lakeside,hotel', 1), img('hotel,pool', 2)],
              inclusions: ['Superior room', 'WiFi', 'Pool & gym', 'Parking'],
              exclusions: ['Breakfast ($25 pp)', 'Mini-bar'],
              cancellationPolicy: 'Free cancellation until 24 hours before',
              availability: 'available',
              supplier: {
                name: 'Novotel',
                rating: 4.3,
                reviewCount: 2145,
              },
              roomType: 'Superior',
              mealPlan: 'Room only',
              highlights: ['Budget-friendly', 'Great location', 'Reliable brand'],
            },
          ],
          selectedOptionId: 'hotel-polynesian',
          agentRecommendedOptionId: 'hotel-polynesian',
          notes: 'Polynesian Spa Hotel is perfect for the geothermal experience',
        },
      ],
    },

    // =======================
    // DAY 3: HOBBITON & DEPART
    // =======================
    {
      date: 'Friday 7 Mar 2025',
      dayNumber: 3,
      activities: [
        // Hobbiton Tour
        {
          id: '3-hobbiton',
          title: 'Hobbiton Movie Set Tour',
          type: 'activity',
          time: '9:30 AM',
          duration: '3 hr',
          locked: false,
          location: {
            id: 'hobbiton',
            name: 'Hobbiton, Matamata',
            coordinates: [-37.8722, 175.6831],
          },
          options: [
            {
              id: 'hob-premium',
              name: 'Hobbiton Evening Banquet Tour',
              description: 'Exclusive evening tour with private banquet feast in the Green Dragon Inn. Limited availability!',
              price: 245,
              statusCredits: 100,
              societePoints: 25,
              photos: [img('hobbiton,evening', 1), img('greendragon,feast', 2), img('hobbit,holes', 3)],
              inclusions: ['Guided tour', 'Banquet feast at Green Dragon Inn', 'Complimentary drink', 'Souvenir photo'],
              exclusions: ['Transport to/from Hobbiton'],
              cancellationPolicy: 'Free cancellation up to 72 hours before',
              availability: 'limited',
              supplier: {
                name: 'Hobbiton Movie Set Tours',
                rating: 4.9,
                reviewCount: 8234,
              },
              highlights: ['Exclusive banquet', 'Evening ambiance', 'Smaller groups'],
            },
            {
              id: 'hob-standard',
              name: 'Hobbiton Movie Set Tour',
              description: 'Guided walking tour through the Shire including the Green Dragon Inn.',
              price: 95,
              statusCredits: 40,
              societePoints: 10,
              photos: [img('hobbiton', 1), img('shire', 2), img('hobbit,house', 3)],
              inclusions: ['2-hour guided tour', 'Complimentary drink at Green Dragon Inn', 'Access to Shire\'s Rest Cafe'],
              exclusions: ['Transport', 'Souvenirs', 'Food'],
              cancellationPolicy: 'Free cancellation up to 24 hours before',
              availability: 'available',
              supplier: {
                name: 'Hobbiton Movie Set Tours',
                rating: 4.9,
                reviewCount: 12450,
              },
              highlights: ['Must-see for LOTR fans', 'Beautiful scenery', 'Photo opportunities'],
            },
          ],
          selectedOptionId: 'hob-standard',
          agentRecommendedOptionId: 'hob-standard',
          notes: 'Standard tour is fantastic value. Evening banquet only if you want the splurge!',
        },

        // Return to Auckland (Locked)
        {
          id: '3-return',
          title: 'Return to Auckland Airport',
          type: 'transfer',
          time: '2:00 PM',
          duration: '2.5 hr',
          locked: true,
          location: {
            id: 'akl-airport-dep',
            name: 'Auckland Airport',
            coordinates: [-37.0082, 174.7850],
          },
          options: [
            {
              id: 'return-drive',
              name: 'Self-drive return',
              description: 'Return rental car at airport and check in for flight',
              price: 0,
              statusCredits: 0,
              societePoints: 0,
              photos: [img('airport', 1)],
              inclusions: ['Route guidance', 'Car return instructions'],
              exclusions: ['Rental car fee (separate)', 'Fuel'],
              cancellationPolicy: 'N/A',
              availability: 'available',
            },
          ],
          selectedOptionId: 'return-drive',
          agentRecommendedOptionId: 'return-drive',
        },
      ],
    },
  ],

  summary: {
    subtotal: 2845,
    statusCredits: 1155,
    societePoints: 289,
    taxes: 285,
    fees: 50,
    total: 3180,
    currency: 'USD',
    originalPricing: {
      subtotal: 2845,
      statusCredits: 1155,
      societePoints: 289,
      taxes: 285,
      fees: 50,
      total: 3180,
      currency: 'USD',
    },
    changeCount: 0,
  },
};
